from flask import Flask, render_template, request
import sqlite3
import requests
from error_data import error_database

app = Flask(__name__)

DATABASE = "errors.db"


# ---------------- DATABASE ---------------- #

def init_db():
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS errors (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            error_text TEXT UNIQUE,
            why TEXT,
            causes TEXT,
            fix TEXT
        )
    """)
    conn.commit()
    conn.close()


def get_error_from_db(error_text):
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("SELECT why FROM errors WHERE error_text=?", (error_text,))
    result = cursor.fetchone()
    conn.close()
    return result


def save_error_to_db(error_text, explanation):
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute(
        "INSERT OR IGNORE INTO errors (error_text, why, causes, fix) VALUES (?, ?, ?, ?)",
        (error_text, explanation, "Generated by AI", "See explanation above.")
    )
    conn.commit()
    conn.close()


# ---------------- ROUTE ---------------- #

@app.route("/", methods=["GET", "POST"])
def home():
    result = None

    if request.method == "POST":
        user_error = request.form.get("error_message", "").strip().lower()

        if not user_error:
            return render_template("index.html", result=None)

        # 1️⃣ Static dictionary check
        for error in error_database.values():
            if any(keyword in user_error for keyword in error["keywords"]):
                return render_template("index.html", result=error)

        # 2️⃣ Database check
        db_result = get_error_from_db(user_error)
        if db_result:
            result = {
                "why": db_result[0],
                "causes": ["Stored from previous AI response"],
                "fix": "See explanation above."
            }
            return render_template("index.html", result=result)

        # 3️⃣ Ollama API call
        try:
            response = requests.post(
                "http://127.0.0.1:11434/api/generate",
                json={
                    "model": "phi3:latest",   # change if needed
                    "prompt": f"Explain this programming error clearly and simply:\n\n{user_error}",
                    "stream": False
                },
                timeout=120
            )

            response.raise_for_status()
            api_json = response.json()

            if "response" not in api_json:
                raise Exception("Invalid Ollama response format")

            ai_text = api_json["response"].strip()

        except requests.exceptions.ConnectionError:
            return render_template(
                "index.html",
                result={
                    "why": "Ollama Not Running",
                    "causes": ["Cannot connect to Ollama server."],
                    "fix": "Run: ollama serve"
                }
            )

        except requests.exceptions.Timeout:
            return render_template(
                "index.html",
                result={
                    "why": "Ollama Timeout",
                    "causes": ["Model still loading or system slow."],
                    "fix": "Wait and try again."
                }
            )

        except Exception as e:
            return render_template(
                "index.html",
                result={
                    "why": "Ollama Error",
                    "causes": [str(e)],
                    "fix": "Check Ollama installation."
                }
            )

        # Direct display (NO fragile parsing)
        result = {
            "why": ai_text,
            "causes": ["Generated by AI"],
            "fix": "See explanation above."
        }

        save_error_to_db(user_error, ai_text)

    return render_template("index.html", result=result)


# ---------------- RUN APP ---------------- #

if __name__ == "__main__":
    init_db()
    app.run(debug=True)