from flask import Flask, render_template, request
import sqlite3
import requests
import json
import os
from error_data import error_database

app = Flask(__name__)

DATABASE = "errors.db"
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")


# ---------------- DATABASE ---------------- #

def init_db():
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS errors (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            error_text TEXT UNIQUE,
            why TEXT,
            causes TEXT,
            fix TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.commit()
    conn.close()


def get_error_from_db(error_text):
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT why, causes, fix FROM errors WHERE error_text=?",
        (error_text,)
    )
    result = cursor.fetchone()
    conn.close()
    return result


def save_error_to_db(error_text, why, causes, fix):
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute(
        "INSERT OR IGNORE INTO errors (error_text, why, causes, fix) VALUES (?, ?, ?, ?)",
        (error_text, why, json.dumps(causes), fix)
    )
    conn.commit()
    conn.close()


def get_all_cached_errors():
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT error_text, why, created_at FROM errors ORDER BY created_at DESC LIMIT 10"
    )
    rows = cursor.fetchall()
    conn.close()
    return rows


# ---------------- AI ---------------- #

def ask_claude(error_text):
    if not ANTHROPIC_API_KEY:
        raise ValueError("ANTHROPIC_API_KEY environment variable not set.")

    prompt = f"""You are a helpful programming tutor. A user got this error:

{error_text}

Respond ONLY with a JSON object (no markdown, no explanation outside the JSON) in this exact format:
{{
  "why": "One clear sentence explaining what this error means in plain English.",
  "causes": ["Cause 1", "Cause 2", "Cause 3"],
  "fix": "A practical, specific suggestion for how to fix or debug this error."
}}"""

    response = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json"
        },
        json={
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 512,
            "messages": [{"role": "user", "content": prompt}]
        },
        timeout=30
    )
    response.raise_for_status()

    content = response.json()["content"][0]["text"].strip()

    if content.startswith("```"):
        content = content.split("```")[1]
        if content.startswith("json"):
            content = content[4:]

    return json.loads(content)


def ask_ollama(error_text):
    response = requests.post(
        "http://127.0.0.1:11434/api/generate",
        json={
            "model": "phi3:latest",
            "prompt": (
                f"Explain this programming error clearly and simply. "
                f"Reply ONLY with a JSON object with keys: why, causes (array), fix.\n\n{error_text}"
            ),
            "stream": False
        },
        timeout=120
    )
    response.raise_for_status()
    api_json = response.json()

    if "response" not in api_json:
        raise Exception("Invalid Ollama response format")

    raw = api_json["response"].strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {
            "why": raw,
            "causes": ["Generated by AI"],
            "fix": "See explanation above."
        }


# ---------------- ROUTE ---------------- #

@app.route("/", methods=["GET", "POST"])
def home():
    result = None
    source = None
    history = get_all_cached_errors()

    if request.method == "POST":
        user_error = request.form.get("error_message", "").strip()
        normalized = user_error.lower()

        if not normalized:
            return render_template("index.html", result=None, history=history)

        # 1. Static dictionary check
        for error in error_database.values():
            if any(keyword in normalized for keyword in error["keywords"]):
                return render_template("index.html", result=error, source="local", history=history)

        # 2. Database cache check
        db_result = get_error_from_db(normalized)
        if db_result:
            why, causes_json, fix = db_result
            try:
                causes = json.loads(causes_json)
            except (json.JSONDecodeError, TypeError):
                causes = [causes_json]
            return render_template("index.html", result={"why": why, "causes": causes, "fix": fix}, source="cache", history=history)

        # 3. AI call
        try:
            if ANTHROPIC_API_KEY:
                parsed = ask_claude(normalized)
                source = "claude"
            else:
                parsed = ask_ollama(normalized)
                source = "ollama"

            result = {
                "why": parsed.get("why", "No explanation returned."),
                "causes": parsed.get("causes", ["Unknown"]),
                "fix": parsed.get("fix", "See explanation above.")
            }
            save_error_to_db(normalized, result["why"], result["causes"], result["fix"])

        except ValueError as e:
            result = {"why": str(e), "causes": ["Set ANTHROPIC_API_KEY or install Ollama."], "fix": "export ANTHROPIC_API_KEY=your_key_here"}
            source = "error"
        except requests.exceptions.ConnectionError:
            result = {"why": "Could not connect to AI service.", "causes": ["Ollama not running and no Claude API key set."], "fix": "Run: ollama serve — or set your ANTHROPIC_API_KEY."}
            source = "error"
        except requests.exceptions.Timeout:
            result = {"why": "AI request timed out.", "causes": ["Model still loading or system slow."], "fix": "Wait and try again."}
            source = "error"
        except Exception as e:
            result = {"why": "Unexpected error.", "causes": [str(e)], "fix": "Check your API key and internet connection."}
            source = "error"

    return render_template("index.html", result=result, source=source, history=history)


# ---------------- RUN ---------------- #

if __name__ == "__main__":
    init_db()
    app.run(debug=True)